
[config]
default_to_workspace = false

[tasks.build]
description = "Build the project"
command = "cargo"
args = ["build"]

[tasks.release]
description = "Build the project in release mode"
command = "cargo"
args = ["build", "--release"]

[tasks.test]
description = "Run tests"
command = "cargo"
args = ["test"]

[tasks.fmt]
description = "Format code using rustfmt"
toolchain = "nightly-2025-08-07"
command = "cargo"
args = ["fmt", "--all"]

[tasks.fmt-check]
description = "Format code using rustfmt"
toolchain = "nightly-2025-08-07"
command = "cargo"
args = ["fmt", "--check", "--all"]

[tasks.lint]
description = "Run Clippy linter"
workspace = false
command = "cargo"
args = ["clippy", "--workspace", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.clean]
description = "Clean the project"
command = "cargo"
args = ["clean"]

[tasks.preflight]
description = "Runs the CI test scripts"
script = [
    "cd modules/c-wrapper/scripts && sh build-docker.sh",
    "cd modules/core && docker build -t rust-onnx-runtime .",
    "cd modules/core && docker run --rm rust-onnx-runtime cargo test --features onnx-tests",
    "cd modules/core && docker run --rm rust-onnx-runtime cargo test --features tensorflow-tests",
    "cd modules/core && docker run --rm rust-onnx-runtime cargo test --features sklearn-tests",
    "cd modules/core && docker run --rm rust-onnx-runtime cargo test --features torch-tests"
]

[env]
RUST_BACKTRACE = "1"
