[package]
name = "c-wrapper"
version = "0.1.4"
edition = "2021"
description = "A Rust wrapper crate providing C bindings for SurrealML."
license-file = "LICENSE"

[dependencies]
surrealml-core = { path = '../core', features = ["dynamic"] }
uuid = { workspace = true, features = ["v4"] }
ndarray = { workspace = true }

# for the uploading the model to the server
tokio = { workspace = true, features = ["full"] }
hyper = { workspace = true, features = ["full"] }
base64 = {  workspace = true }
zip = {workspace = true}

[lib]
crate-type = ["cdylib"]
