version: "3.8"

services:
  linux_surrealml_core:
    build:
      context: .
      dockerfile: builds/Dockerfile.linux
    restart: unless-stopped
    # command: tail -f /dev/null
    environment:
      TEST: test_env
    volumes:
      - ./output/linux:/app/output
    ports:
      - "8001:8001"
