version: "3.8"

services:
  surrealml_core:
    build:
      context: .
      dockerfile: builds/Dockerfile.macos
    restart: unless-stopped
    environment:
      TEST: test_env
    ports:
      - "8001:8001"
