[package]
name    = "wasm-wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
surrealml-tokenizers = { path = "../tokenizers" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wit-bindgen-rt = "0.42.1"

[lib]
crate-type = ["cdylib"]     

