[package]
name = "wasm-linker"
version = "0.1.0"
edition = "2024"

[dependencies]
surrealml-tokenizers = { path = "../tokenizers", features = ["http-access"] }
surrealml-llms = { path = "../llms" }
wasmtime = "34.0.2"
wasmtime-wasi = { version = "34.0.2", features = ["preview1"] }
bytemuck = "1.23.2"

[lints]
workspace = true
