name: Run linting

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test_core:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check with Clippy
      run: cargo clippy
