name: Release core to crates

on:
  workflow_dispatch:
    # inputs:
    #   version:
    #     description: 'Release version (e.g., 1.2.3)'
    #     required: true

permissions:
  contents: write
  deployments: write
  actions: write
  packages: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      actions: write
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Update Cargo.toml version
        run: |
          cd modules/core
          cargo install cargo-version-upgrade
          cargo-version-upgrade patch
        shell: bash

      - name: Commit and Tag Version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add modules/core/Cargo.toml
          git commit -m "chore(core): bump version to ${{ inputs.version }}"
          git tag core-v${{ inputs.version }}
          git push origin main --tags
        shell: bash

      - name: Publish to crates.io
        run: |
          cd modules/core
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        shell: bash
